cluster: "pbs-submit.py --depend \"{dependencies}\""
cluster-status: "pbs-status.py"
jobscript: "pbs-jobscript.sh"
jobs: 5000
immediate-submit: {{cookiecutter.immediate_submit}}
verbose: true
notemp: true
